/*
 * `/llms.txt` - the manual as a list an agent can choose from.
 *
 * The sections and the sentence under each document are read from
 * `docs/README.md`, the file the sidebar and the header are built from, so a
 * page added to the manual is listed here too and nothing has to be kept in
 * step by hand. What the file opens with is in `../llms.mjs`.
 *
 * Every entry links to the Markdown source rather than to the page, because
 * the reader of this file wants the document and not the layout around it.
 *
 * The order is not the sidebar's. The generated files come first, because a
 * reader that wants to call a node is best served by the OpenAPI document and
 * the full text, and the sections a client author does not need close the
 * file under `Optional`, which is the heading the llms.txt convention names
 * for what a reader short of room can skip.
 */

import type { APIRoute } from 'astro';

import { FULL, OPENAPI, PREAMBLE, siteUrl, sourceUrl } from '../llms.mjs';

/**
 * The manual as headed lists, defined into the bundle by `astro.config.mjs`
 * from what `../parts.mjs` reads. A page is rendered from a bundle and cannot
 * read the repository, which is why it arrives as a constant.
 */
declare const __DOCS_CATALOGUE__: {
	label: string;
	items: { label: string; slug: string; description: string }[];
}[];

const CATALOGUE = __DOCS_CATALOGUE__;

/*
 * The sections that answer questions a client author does not have: how to
 * run nodes, what to monitor, and why the engine is built as it is. They are
 * named by the label `../sidebar.mjs` gives them, which is the `##` heading
 * of `docs/README.md` followed by the `###` heading under it, and a label
 * here that the index no longer has fails the build rather than quietly
 * promoting a section back into the main list.
 */
const OPTIONAL = [
	'How-to guides: Running a deployment',
	'How-to guides: Operating a deployment',
	'Explanation'
];

/*
 * The parts of the API that are not documents in `docs/`. The endpoint pages
 * and the OpenAPI document are generated by the site build, and the full text
 * is the file next to this one.
 */
const MACHINE_READABLE = [
	{
		label: 'OpenAPI document',
		href: OPENAPI,
		description: 'Every endpoint with its request and its response, written by the engine build. Generate a client from this.'
	},
	{
		label: 'Full text for client authors',
		href: FULL,
		description: 'The guides for defining an index, indexing and searching it, and handling errors, then the API reference, in one file.'
	},
	{
		label: 'REST API pages',
		href: siteUrl('/api/'),
		description: 'A page per endpoint, generated from the OpenAPI document.'
	}
];

export const GET: APIRoute = () => {
	const missing = OPTIONAL.filter(label => !CATALOGUE.some(listing => listing.label === label));
	if(missing.length > 0) {
		throw new Error(`llms.txt marks sections as optional that docs/README.md does not have: ${missing.join(', ')}`);
	}

	const machineReadable = [
		'## Machine-readable',
		'',
		...MACHINE_READABLE.map(item => entry(item.label, item.href, item.description)),
		''
	].join('\n');

	const sections = CATALOGUE
		.filter(listing => !OPTIONAL.includes(listing.label))
		.map(listing => [
			`## ${listing.label}`,
			'',
			...listing.items.map(item => entry(item.label, sourceUrl(item.slug), item.description)),
			''
		].join('\n'));

	const optional = [
		'## Optional',
		'',
		'How to run and operate nodes, and why the engine is built as it is. A reader calling a node that someone else runs can skip these.',
		'',
		...CATALOGUE
			.filter(listing => OPTIONAL.includes(listing.label))
			.map(listing => [
				`**${listing.label}**`,
				'',
				...listing.items.map(item => entry(item.label, sourceUrl(item.slug), item.description)),
				''
			].join('\n'))
	].join('\n');

	return new Response([PREAMBLE, machineReadable, ...sections, optional].join('\n'), {
		headers: { 'content-type': 'text/plain; charset=utf-8' }
	});
};

/** One list entry, with the description only where the index carries one. */
function entry(label: string, href: string, description: string) {
	return description ? `- [${label}](${href}): ${description}` : `- [${label}](${href})`;
}
