package se.l4.exofind.engine.api.v1alpha1.admin.model;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a field containing text data.
 *
 * <p>Field usages are opt-in, each enabled by including its configuration
 * object. An empty object enables a usage with engine defaults:
 *
 * <pre>
 * {
 *   "type": "string",
 *   "filter": {},
 *   "matching": { "highlight": {} }
 * }
 * </pre>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = """
	Represents text data. Field usages are opt-in, each enabled by including \
	its configuration object. An empty object enables a usage with engine \
	defaults. See \
	[`string`](https://exofind.dev/reference/field-types/#string).""")
public record StringFieldDefinition(
	/**
	 * What the field is for, expanded into the usages that serve it before the
	 * definition is stored. Accepts {@code id}, {@code title},
	 * {@code description}, {@code tag}, {@code path} and {@code code}.
	 */
	@Schema(description = FieldDefinition.ROLE_DESCRIPTION)
	Role role,

	@Schema(description = FieldDefinition.PRIMARY_KEY_DESCRIPTION, defaultValue = "false")
	Boolean primaryKey,

	@Schema(description = FieldDefinition.REQUIRED_DESCRIPTION, defaultValue = "false")
	Boolean required,

	@Schema(description = FieldDefinition.MULTIPLE_DESCRIPTION, defaultValue = "false")
	Boolean multiple,

	@Schema(description = FieldDefinition.STORED_DESCRIPTION, defaultValue = "false")
	Boolean stored,

	@Schema(description = FieldDefinition.LOCALES_DESCRIPTION)
	Locales locales,

	@Schema(description = FieldDefinition.FILTER_DESCRIPTION)
	Filter filter,

	@Schema(description = FieldDefinition.SORT_DESCRIPTION)
	Sort sort,

	@Schema(description = FieldDefinition.FACET_DESCRIPTION)
	Facet facet,

	/**
	 * Configures exact-match normalization for filtering.
	 */
	@Schema(description = "Configures exact-match normalization for filtering.")
	Keyword keyword,

	/**
	 * Enables full-text search with analyzed terms.
	 */
	@Schema(description = """
		Enables full-text search with analyzed terms.""")
	TextUsage matching,

	/**
	 * Enables prefix matching for as-you-type search queries.
	 */
	@Schema(description = """
		Enables prefix matching for as-you-type search queries. A field \
		defined only for `autocomplete` does not support phrase matching.""")
	TextUsage autocomplete,

	/**
	 * Enables path hierarchy matching (for example, `Men/Shoes/Running`).
	 */
	@Schema(description = """
		Enables path hierarchy matching (for example, `Men/Shoes/Running`). \
		Facets on hierarchy fields return nested counts per level, and the \
		`under` matcher filters to a level and all sub-levels.""")
	Hierarchy hierarchy
) implements FieldDefinition {
	/**
	 * Enables path hierarchy matching.
	 */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Schema(description = "Enables path hierarchy matching.")
	public record Hierarchy(
		/**
		 * Specifies the delimiter between hierarchy levels. Defaults to `/`.
		 * Changing the separator on an index holding documents requires
		 * reindexing them.
		 */
		@Schema(
			description = """
				Specifies the string that separates hierarchy levels. Changing \
				the separator on an index that contains documents requires \
				reindexing them.""",
			defaultValue = "/"
		)
		String separator
	) {
	}

	/**
	 * Configures exact-match normalization for filtering.
	 */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Schema(description = "Configures exact-match normalization for filtering.")
	public record Keyword(
		/**
		 * When `true`, folds case before values are compared, allowing filters
		 * on `Fiction` to match `fiction`. Defaults to true.
		 */
		@Schema(
			description = """
				When `true`, folds case before values are compared, allowing \
				filters on `Fiction` to match `fiction`.""",
			defaultValue = "true"
		)
		Boolean caseFolding
	) {
	}

	/**
	 * Configuration properties shared by the `matching` and `autocomplete`
	 * usages. The usage type determines the default analyzer configuration
	 * generated by the engine when no analyzer is explicitly provided.
	 */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Schema(description = """
		Configuration properties shared by the `matching` and `autocomplete` \
		usages. The usage type determines the default analyzer configuration \
		generated by the engine when no analyzer is explicitly provided.""")
	public record TextUsage(
		/**
		 * Specifies how the text of this usage is analyzed. If omitted, the
		 * engine generates an analyzer based on the field usage and locale.
		 */
		@Schema(description = """
			Specifies how the text of this usage is analyzed. If omitted, the \
			engine generates an analyzer based on the field usage and locale. \
			See [Analysis](https://exofind.dev/reference/analysis/).""")
		AnalyzerDefinition analyzer,

		/**
		 * Relative score weight of hits in this field when querying across
		 * multiple fields. Defaults to 1.
		 */
		@Schema(
			description = """
				Relative score weight of hits in this field when querying \
				across multiple fields.""",
			defaultValue = "1"
		)
		Float weight,

		/**
		 * Enables highlighted snippet extraction in search responses. Text is
		 * stored for highlighting regardless of whether the field is configured
		 * as stored.
		 */
		@Schema(description = """
			Enables highlighted snippet extraction in search responses. Text \
			is stored for highlighting regardless of the `stored` property. \
			Highlighting targets `matching` when defined; `highlight` on \
			`autocomplete` takes effect only when `matching` is omitted.""")
		Highlight highlight,

		/**
		 * Enables typo tolerance for matching search terms, including prefixes
		 * currently being typed.
		 */
		@Schema(description = """
			Enables typo tolerance for matching search terms, including \
			prefixes currently being typed.""")
		TypoTolerance typoTolerance,

		/**
		 * Controls compound word splitting in the engine-generated chain. If
		 * omitted, splitting is determined by the locale of the value.
		 * Supported only when using engine-generated analyzers; custom
		 * analyzers configured via {@code analyzer} define their own
		 * decompounding behavior.
		 */
		@Schema(description = """
			Controls compound word splitting in the engine-generated chain. If \
			omitted, splitting is determined by the locale of the value. \
			Supported only when using engine-generated analyzers; custom \
			analyzers specified via `analyzer` define their own decompounding \
			behavior. See [Compound \
			words](https://exofind.dev/reference/analysis/#compound-words).""")
		Decompound decompound,

		/**
		 * Boosts documents where the query matches the full field value,
		 * ranking full-field matches higher than partial matches.
		 */
		@Schema(description = """
			Boosts documents where the query matches the full field value. \
			Adjusts ranking only without modifying hit counts or facet \
			distributions; analyzer normalization is applied before the \
			comparison.""")
		Exact exact,

		/**
		 * Controls the field length penalty in ranking. If omitted, defaults to
		 * {@code moderate}.
		 */
		@Schema(
			description = """
				Controls the field length penalty in ranking. Changes take \
				effect at search time without reindexing.""",
			defaultValue = "moderate"
		)
		LengthNormalization lengthNormalization
	) {
		/**
		 * Enables highlighted snippet extraction within matching text.
		 */
		@JsonInclude(JsonInclude.Include.NON_NULL)
		@Schema(description = """
			Enables highlighted snippet extraction within matching text. \
			Contains no configuration properties.""")
		public record Highlight() {
		}

		/**
		 * Configures score boosting for queries matching the full field value.
		 */
		@JsonInclude(JsonInclude.Include.NON_NULL)
		@Schema(description = """
			Configures score boosting for queries matching the full field \
			value.""")
		public record Exact(
			/**
			 * Score boost multiplier applied when a query matches the full
			 * field value. Defaults to 2.
			 */
			@Schema(
				description = """
					Score boost multiplier applied when a query matches the \
					full field value.""",
				defaultValue = "2"
			)
			Float boost
		) {
		}

		/**
		 * Controls the field length penalty applied during ranking to favor
		 * shorter matches over longer text.
		 */
		@Schema(description = """
			Controls the field length penalty in ranking: `none` applies no \
			penalty, `moderate` applies standard prose normalization, and \
			`strong` applies the full penalty for short fields such as titles.""")
		public enum LengthNormalization {
			/**
			 * Length is not counted at all, for a field where a longer value
			 * is not a worse answer, only a fuller one.
			 */
			@JsonProperty("none")
			NONE,

			/**
			 * Length counts the way it does for prose, which is what the
			 * engine does when nothing says otherwise.
			 */
			@JsonProperty("moderate")
			MODERATE,

			/**
			 * Length counts fully, for a field holding names rather than
			 * prose.
			 */
			@JsonProperty("strong")
			STRONG
		}

		/**
		 * Controls compound word splitting in the engine-generated analyzer
		 * chain.
		 */
		@Schema(description = """
			Controls compound word splitting in the engine-generated analyzer \
			chain. Set to `none` to disable splitting.""")
		public enum Decompound {
			/**
			 * Never split, whatever the locale.
			 */
			@JsonProperty("none")
			NONE
		}

		/**
		 * Enables typo tolerance for term matching.
		 */
		@JsonInclude(JsonInclude.Include.NON_NULL)
		@Schema(description = """
			Enables typo tolerance. Mixed alphanumeric words follow standard \
			length thresholds.""")
		public record TypoTolerance(
			/**
			 * Minimum word length required to allow one typo. Defaults to 5.
			 */
			@Schema(
				description = "Minimum word length required to allow one typo.",
				defaultValue = "5"
			)
			Integer minLengthOneTypo,

			/**
			 * Minimum word length required to allow two typos. Defaults to 9
			 * for `matching`. In `autocomplete`, two typos are permitted only
			 * when explicitly configured.
			 */
			@Schema(
				description = """
					Minimum word length required to allow two typos. In \
					`autocomplete`, two typos are permitted only when \
					explicitly configured.""",
				defaultValue = "9"
			)
			Integer minLengthTwoTypos,

			/**
			 * Number of leading characters that must match exactly. Defaults to
			 * 1.
			 */
			@Schema(
				description = "Number of leading characters that must match exactly.",
				defaultValue = "1"
			)
			Integer prefixLength,

			/**
			 * Enables typo tolerance for digit-only words. If omitted,
			 * digit-only words require exact matches regardless of length.
			 */
			@Schema(description = """
				Enables typo tolerance for digit-only words. If omitted, \
				digit-only words require exact matches regardless of length.""")
			Numbers numbers
		) {
			/**
			 * Enables typo tolerance for digit-only words.
			 */
			@JsonInclude(JsonInclude.Include.NON_NULL)
			@Schema(description = """
				Enables typo tolerance for digit-only words. Contains no \
				configuration properties.""")
			public record Numbers() {
			}
		}
	}
}
